//=============================================================================
//VERY SIMPLE USERNAME AND PASSWORD SCHEMA WITH PASSWORD HASH
//=============================================================================
var mongoose = require( 'mongoose' );
var schema = mongoose.Schema;

var topicSchema = new schema( {
	text:     { type: String, required: true, index: { unique: true } },
	html:     { type: String },
	category: { type: String, required: true },
	type:     { type: String, required: true },
	deltas:   { type: String, required: true, default: 0 },
	sames:    { type: String, required: true, default: 0 },
	flags:    { type: String, required: true, default: 0 }
});

var Topic = mongoose.model( 'topic', topicSchema )

var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Does human nature make communism impossible?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is it possible to be an anarchist without opposing hierarchy?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is anarcho-capitalism a type of anarchism?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'How did capitalism come to be?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Do economic classes exist? If so, what are they?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Imagine that there is a runaway trolley barrelling down a railway. Ahead there are five people tied up and unable to move. The trolley is headed straight for them. You are standing some distance off in the train yard, next to a lever. If you pull this lever, the trolley will switch to a different set of tracks. Unfortunately, there is one person on the side track. You have two options: (1) Do nothing, and the trolley kills the five people on the main track. (2) Pull the lever, diverting the trolley onto the side track where it will kill one person. Which is the correct choice?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is software freedom important?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What role is bitcoin likely to play in the future of finance?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is it reasonable to expect the poor to pick themselves up by their bootstraps?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What role are cryptocurrencies likely to play in the future of finance?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Should some criminals be put to death?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is political moderatism generally preferable to radicalism?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Does patriarchy exist?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Do animals have rights?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is human sensory information (including science) a reliable means to affirming authorative truth?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is it possible to arrive at any authorative truth?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Are extremist political beliefs neccesarily incorrect, unethical, or otherwise undesirable?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Does education need an overhaul? If so, what changes should be made to our educational systems?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Does the prison system need an overhaul? If so, what changes should be made to our prisons?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is it possible to replace every component of an object, and have it remain the same object?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'If a tree falls in the woods and there is no one there to hear it, does it make a sound?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Why is there something rather than nothing?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'For what purpose do people exist?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is economics a science?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Are the soft sciences actual sciences?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Does the universe exist?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What is free will, and do we have it?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Do a god or gods exist? If so, what is/are they like?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What is the ideal moral system?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Can anything really be experienced objectively?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What are numbers?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What is the best way to organize a society?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What is the best way to organize a society?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Do events actually occur if they are not observed?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Where were people before they were born?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Why do we call some belief systems “mythologies” (ancient Greek, Norse, Egyptian, etc.) and others religions?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'What should be the role of sex in society?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'In what circumstances is it ethical to kill a human being?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is internet piracy unethical?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is internet piracy bad for the arts?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is animal testing wrong?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Should higher education be made freely availible?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is theft wrong?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();
var newTopic = new Topic( { text: '', category: '', type: '' } );
	newTopic.text     = 'Is theft an effective way to create change in society?';
	newTopic.category = 'philosophy';
	newTopic.type     = 'question';
	newTopic.save();



//export this model
module.exports = mongoose.model( 'topic', topicSchema );
